name: Publish docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Install wasm-gc
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: install
          args: --git https://github.com/alexcrichton/wasm-gc --force

      - name: Build wasm and native code
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release


